In [4]:
# supervised Learning --learns from labelled data(input and output)
# types:
# regression--if the target column is continuous value(numeric value) ex:salary prediction
# classification--if the target column is classes or binary ex:thyroid prediction
# unsupervised Learning--learns from unlabelled data
# clustering
# dimenstionality reduction

In [5]:
# ML steps
# Data collection
# Data cleaning & visualization
# Encoding
# labelling the data(x as input ,y as output)
# splitting the data to training and testing(80% for training, 20% for testing)
#     *x_train,x_test,y_train,y_test
# Model building(algorithm)
# Model training
# Model testing
# Model evaluation-(Accuracy,prediction)
# Model deployment

In [6]:
import pandas as pd
df=pd.read_csv("ipl.csv")
df

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [7]:

print("min date",df['date'].min())
print("max date",df['date'].max())

min date 2008-04-18
max date 2017-05-21

In [8]:
df.isnull().sum()

mid               0
date              0
venue             0
bat_team          0
bowl_team         0
batsman           0
bowler            0
runs              0
wickets           0
overs             0
runs_last_5       0
wickets_last_5    0
striker           0
non-striker       0
total             0
dtype: int64

In [9]:
df.dtypes

mid                 int64
date               object
venue              object
bat_team           object
bowl_team          object
batsman            object
bowler             object
runs                int64
wickets             int64
overs             float64
runs_last_5         int64
wickets_last_5      int64
striker             int64
non-striker         int64
total               int64
dtype: object

In [10]:
df.columns

Index(['mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler',
       'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker',
       'non-striker', 'total'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76014 entries, 0 to 76013
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mid             76014 non-null  int64
 1   date            76014 non-null  object
 2   venue           76014 non-null  object
 3   bat_team        76014 non-null  object
 4   bowl_team       76014 non-null  object
 5   batsman         76014 non-null  object
 6   bowler          76014 non-null  object
 7   runs            76014 non-null  int64
 8   wickets         76014 non-null  int64
 9   overs           76014 non-null  float64
 10  runs_last_5     76014 non-null  int64
 11  wickets_last_5  76014 non-null  int64
 12  striker         76014 non-null  int64
 13  non-striker     76014 non-null  int64
 14  total           76014 non-null  int64
dtypes: float64(1), int64(8), object(6)
memory usage: 8.7+ MB

DATA CLEANING
Points covered under this section:
• Removing unwanted columns
• Keeping only consistent teams
• Removing the first 5 overs data in every match
• Converting the column 'date' from string into datetime object

In [12]:
df.columns

Index(['mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler',
       'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker',
       'non-striker', 'total'],
      dtype='object')

In [13]:
# removing unwanted columns
columns_to_remove=['mid','venue','batsman','bowler','striker','non-striker']
print("Before Removing unwanted columns:",df.shape)

df.drop(labels=columns_to_remove,axis=1,inplace=True)
print("After Removing unwanted columns:",df.shape)

Before Removing unwanted columns: (76014, 15)
After Removing unwanted columns: (76014, 9)

In [14]:
df.columns

Index(['date', 'bat_team', 'bowl_team', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5', 'total'],
      dtype='object')

In [15]:
# keeping only consistent teams
df['bat_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [16]:
consistent_teams=['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals','Mumbai Indians','Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils','Sunrisers Hyderabad']

print("Before Removing inconsistent teams:",df.shape)

df=df[(df['bat_team'].isin(consistent_teams))&(df['bowl_team'].isin(consistent_teams))]
print("After Removing inconsistent teams:",df.shape)

Before Removing inconsistent teams: (76014, 9)
After Removing inconsistent teams: (53811, 9)

In [17]:
# Removing the first 5 overs data in every match
df['overs'].unique()

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  5.1,  5.2,
        5.3,  5.4,  5.5,  5.6,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  7.1,
        7.2,  7.3,  7.4,  7.5,  7.6,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        9.1,  9.2,  9.3,  9.4,  9.5,  9.6, 10.1, 10.2, 10.3, 10.4, 10.5,
       10.6, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.1, 12.2, 12.3, 12.4,
       12.5, 12.6, 13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 16.1, 16.2,
       16.3, 16.4, 16.5, 16.6, 17.1, 17.2, 17.3, 17.4, 17.5, 17.6, 18.1,
       18.2, 18.3, 18.4, 18.5, 18.6, 19.1, 19.2, 19.3, 19.4, 19.5, 19.6,
       12. ,  4. ,  7. , 19. ,  0. , 15. ,  1. , 18. ,  2. , 11. , 14. ,
        6. ,  5. ,  9. , 13. , 16. ,  8. , 17. , 10. ])

In [18]:
print("Before Removing first 5 overs teams:",df.shape)
df=df[df['overs']>=5.0]
print("After Removing first 5 overs teams:",df.shape)

Before Removing first 5 overs teams: (53811, 9)
After Removing first 5 overs teams: (40108, 9)

In [19]:
df

,date,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total
32,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,0,5.1,59,0,222
33,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.2,59,1,222
34,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.3,59,1,222
35,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.4,59,1,222
36,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.5,58,1,222
...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,Kolkata Knight Riders,Mumbai Indians,106,9,18.1,29,4,107
75885,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.2,29,4,107
75886,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.3,28,4,107
75887,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.4,24,4,107
75888,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,10,18.5,23,5,107

In [20]:
# converting date object to datetime object
from datetime import datetime
print("Before converting 'date' column from string to datetime:",type(df.iloc[0,0]))

df['date']=df['date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d'))

print("After converting 'date' column from string to datetime:",type(df.iloc[0,0]))

Before converting 'date' column from string to datetime: <class 'str'>
After converting 'date' column from string to datetime: <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [21]:
df.dtypes

date              datetime64[ns]
bat_team                  object
bowl_team                 object
runs                       int64
wickets                    int64
overs                    float64
runs_last_5                int64
wickets_last_5             int64
total                      int64
dtype: object

In [22]:
df=pd.get_dummies(data=df,columns=['bat_team','bowl_team'],dtype='int')
df

,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,bat_team_Chennai Super Kings,bat_team_Delhi Daredevils,bat_team_Kings XI Punjab,...,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
32,2008-04-18,61,0,5.1,59,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
33,2008-04-18,61,1,5.2,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34,2008-04-18,61,1,5.3,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
35,2008-04-18,61,1,5.4,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
36,2008-04-18,61,1,5.5,58,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,106,9,18.1,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75885,2017-05-19,107,9,18.2,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75886,2017-05-19,107,9,18.3,28,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75887,2017-05-19,107,9,18.4,24,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75888,2017-05-19,107,10,18.5,23,5,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [23]:
df.columns

Index(['date', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'total', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')

In [24]:
# rearranging the columns
df=df[['date','bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils','bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals','bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
      'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils','bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals','bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad','runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5','total']]

In [25]:
df.columns

Index(['date', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5', 'total'],
      dtype='object')

In [26]:
print(df['date'].min())
print(df['date'].max())

2008-04-18 00:00:00
2017-05-19 00:00:00

In [27]:
# Labelling the data
x=df.drop('total',axis=1)

# splitting the data for training and testing
x_train=x[x['date'].dt.year<=2016]  #training inputs(80%)
x_test=x[x['date'].dt.year>=2017]   #testing the input(20%)

x_train.drop('date',axis=1,inplace=True)
x_test.drop('date',axis=1,inplace=True)


# output training and testing
y_train=df[df['date'].dt.year<=2016]['total'].values
y_test=df[df['date'].dt.year>=2017]['total'].values

C:\Users\HP\AppData\Local\Temp\ipykernel_5956\331805791.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train.drop('date',axis=1,inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_5956\331805791.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test.drop('date',axis=1,inplace=True)

In [28]:
print(x_train.shape)
print(x_test.shape)

(37330, 21)
(2778, 21)

In [29]:
print(y_train.shape)
print(y_test.shape)

(37330,)
(2778,)

In [30]:
# model building
# !pip install scikit-learn

In [31]:
from sklearn.linear_model import LinearRegression

# create objct for the class
lr=LinearRegression()

# training the model
lr.fit(x_train,y_train)

LinearRegression()

In [32]:
# model testing
lr_pred=lr.predict(x_test)
lr_pred

array([172.07093429, 175.2197967 , 174.61607874, ..., 100.37504751,
        99.80473879,  93.14382211])

In [33]:
# model evaluation
print("Score of LR on Training Set:",lr.score(x_train,y_train))
print("Score of LR on Testing Set:",lr.score(x_test,y_test))

Score of LR on Training Set: 0.6502133812161468
Score of LR on Testing Set: 0.7522633566350516

In [34]:
import numpy as np
from sklearn.metrics import mean_absolute_error as mae,mean_squared_error as mse
print("---------Linear Regression---------------")
print("Mean Absolute Error(MAE):",mae(y_test,lr_pred))
print("Mean Squared Error(MsE):",mse(y_test,lr_pred))
print("Root Mean Squared Error(RMSE):",np.sqrt(mse(y_test,lr_pred)))

---------Linear Regression---------------
Mean Absolute Error(MAE): 12.118617546193311
Mean Squared Error(MsE): 251.00792310417552
Root Mean Squared Error(RMSE): 15.843229566732141

In [35]:
# accuarcy--85%(above 80% can choose this model) BASED ON ACCURACY CAN CHOOSE THE MODEL
# training score--88%(should be more than 80)   these 2 values should be nearer to each other
# testing score--75%                                   
# error matrics
# mean absolute error--17
# mean square error--222
# root mean square error--20
# if mae and rmse is near to each other can use it

In [36]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()

# training the model
rf.fit(x_train,y_train)

RandomForestRegressor()

In [37]:
# model testing
rf_pred=rf.predict(x_test)
rf_pred

array([187.14, 185.96, 188.39, ..., 117.54, 114.43, 114.47])

In [38]:
# model evaluation
print("Score of RF on Training Set:",rf.score(x_train,y_train))
print("Score of RF on Testing Set:",rf.score(x_test,y_test))

Score of RF on Training Set: 0.9922942538459288
Score of RF on Testing Set: 0.6702550399248198

In [39]:
# error Matrics
from sklearn.metrics import mean_absolute_error as mae,mean_squared_error as mse
print("---------Random Forest Regression---------------")
print("Mean Absolute Error(MAE):",mae(y_test,rf_pred))
print("Mean Squared Error(MsE):",mse(y_test,rf_pred))
print("Root Mean Squared Error(RMSE):",np.sqrt(mse(y_test,rf_pred)))

---------Random Forest Regression---------------
Mean Absolute Error(MAE): 13.756065514758818
Mean Squared Error(MsE): 334.0991322814175
Root Mean Squared Error(RMSE): 18.278378819835677

In [40]:
from sklearn.svm import SVR

svr=SVR()

# training the model
svr.fit(x_train,y_train)

SVR()

In [41]:
# model testing
svr_pred=svr.predict(x_test)
svr_pred

array([168.76358772, 174.61807174, 172.40291379, ..., 121.23345   ,
       118.4923028 , 114.33738668])

In [42]:
# model evaluation
print("Score of SVR on Training Set:",svr.score(x_train,y_train))
print("Score of SVR on Testing Set:",svr.score(x_test,y_test))

Score of SVR on Training Set: 0.5811585311962435
Score of SVR on Testing Set: 0.643444370462407

In [43]:
# error Matrics
from sklearn.metrics import mean_absolute_error as mae,mean_squared_error as mse
print("---------Support Vector Regression---------------")
print("Mean Absolute Error(MAE):",mae(y_test,svr_pred))
print("Mean Squared Error(MsE):",mse(y_test,svr_pred))
print("Root Mean Squared Error(RMSE):",np.sqrt(mse(y_test,svr_pred)))

---------Support Vector Regression---------------
Mean Absolute Error(MAE): 14.474241481155584
Mean Squared Error(MsE): 361.2638276909661
Root Mean Squared Error(RMSE): 19.00694156593759

In [44]:
from sklearn.tree import DecisionTreeRegressor
# create a object for the class
rd=DecisionTreeRegressor()

# training the model
rd.fit(x_train,y_train)

DecisionTreeRegressor()

In [45]:
# model testing
rd_pred=rd.predict(x_test)
rd_pred

array([194., 194., 194., ..., 119., 112., 112.])

In [46]:
# model evaluation
print("Score of DT on Training Set:",rd.score(x_train,y_train))
print("Score of DT on Testing Set:",rd.score(x_test,y_test))

Score of DT on Training Set: 0.9998567447518953
Score of DT on Testing Set: 0.48566313699174835

In [47]:
# error Matrics
from sklearn.metrics import mean_absolute_error as mae,mean_squared_error as mse
print("---------Decison Tree Regressor---------------")
print("Mean Absolute Error(MAE):",mae(y_test,rd_pred))
print("Mean Squared Error(MsE):",mse(y_test,rd_pred))
print("Root Mean Squared Error(RMSE):",np.sqrt(mse(y_test,rd_pred)))

---------Decison Tree Regressor---------------
Mean Absolute Error(MAE): 16.848452123830093
Mean Squared Error(MsE): 521.1285097192225
Root Mean Squared Error(RMSE): 22.828239303967848

In [48]:
x_train.columns

Index(['bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5'],
      dtype='object')

In [49]:
df.columns

Index(['date', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5', 'total'],
      dtype='object')

In [144]:
# create a function for prediction
def predict_score(bat_team='Mumbai Indians',bowl_team='Delhi Daredevils',runs=120,wickets=4,
                 overs=6.2,runs_last_5=33,wickets_last_5=1):
    temp_array=list()
    if bat_team=='Chennai Super Kings':
        temp_array=temp_array+[1,0,0,0,0,0,0,0]

    elif bat_team=='Delhi Daredevils':
        temp_array=temp_array+[0,1,0,0,0,0,0,0]

    elif bat_team=='Kings XI Punjab':
         temp_array=temp_array+[0,0,1,0,0,0,0,0]

    elif bat_team=='Kolkata Knight Riders':
          temp_array=temp_array+[0,0,0,1,0,0,0,0]

    elif bat_team=='Mumbai Indians':
          temp_array=temp_array+[0,0,0,0,1,0,0,0]

    elif bat_team=='Rajasthan Royals':
          temp_array=temp_array+[0,0,0,0,0,1,0,0]

    elif bat_team=='Royal Challengers Bangalore':
          temp_array=temp_array+[0,0,0,0,0,0,1,0]

    elif bat_team=='Sunrisers Hyderabad':
          temp_array=temp_array+[0,0,0,0,0,0,0,1]



    if bowl_team=='Chennai Super Kings':
        temp_array=temp_array+[1,0,0,0,0,0,0,0]

    elif bowl_team=='Delhi Daredevils':
        temp_array=temp_array+[0,1,0,0,0,0,0,0]

    elif bowl_team=='Kings XI Punjab':
         temp_array=temp_array+[0,0,1,0,0,0,0,0]

    elif bowl_team=='Kolkata Knight Riders':
          temp_array=temp_array+[0,0,0,1,0,0,0,0]

    elif bowl_team=='Mumbai Indians':
          temp_array=temp_array+[0,0,0,0,1,0,0,0]

    elif bowl_team=='Rajasthan Royals':
          temp_array=temp_array+[0,0,0,0,0,1,0,0]

    elif bowl_team=='Royal Challengers Bangalore':
          temp_array=temp_array+[0,0,0,0,0,0,1,0]

    elif bowl_team=='Sunrisers Hyderabad':
          temp_array=temp_array+[0,0,0,0,0,0,0,1]

    temp_array=temp_array+[runs,wickets,overs,runs_last_5,wickets_last_5]


    # converting to numpy array
    temp_array=np.array([temp_array])


    # prediction
    return int(lr.predict(temp_array))


    # temp_array = np.array(temp_array).reshape(1, -1)
    # final_score = lr.predict(temp_array)[0]
    # return int(final_score)

In [148]:
final_score = predict_score(
    bat_team='Kolkata Knight Riders',
    bowl_team='Mumbai Indians',
    runs=107,
    wickets=9,
    overs=18.2,
    runs_last_5=29,
    wickets_last_5=4
)

print("Final Predicted Score is {} to {}".format(final_score-5, final_score+10))

Final Predicted Score is 95 to 110

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\HP\AppData\Local\Temp\ipykernel_5956\1242553705.py:63: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(lr.predict(temp_array))

In [152]:
# Kolkata Knight Riders	Royal Challengers Bangalore	61	0	5.1	59	0	222
final_score = predict_score(
    bat_team='Kolkata Knight Riders',
    bowl_team='Royal Challengers Bangalore',
    runs=61,
    wickets=1,
    overs=5.2,
    runs_last_5=59,
    wickets_last_5=1
)

print("Final Predicted Score is {} to {}".format(final_score-5, final_score+10))

Final Predicted Score is 177 to 192

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\HP\AppData\Local\Temp\ipykernel_5956\1242553705.py:63: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(lr.predict(temp_array))

In [154]:
# final_score = predict_score(
#     bat_team='Kolkata Knight Riders',
#     bowl_team='Royal Challengers Bangalore',
#     runs=61,
#     wickets=1,
#     overs=5.2,
#     runs_last_5=59,
#     wickets_last_5=1
# )

# print("Final Predicted Score is {} to {}".format(final_score-5, final_score+10))

# Mam for this data it was showing wrong prediction where b/w 177 and 192 but total was 222

SAVING THE MODEL

In [181]:
final_score = predict_score(
    bat_team='Royal Challengers Bangalore',
    bowl_team='Sunrisers Hyderabad',
    runs=51,
    wickets=0,
    overs=5.3,
    runs_last_5=49,
    wickets_last_5=0
)

print("Final Predicted Score is {} to {}".format(final_score-5, final_score+10))

Final Predicted Score is 178 to 193

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\HP\AppData\Local\Temp\ipykernel_5956\1242553705.py:63: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(lr.predict(temp_array))

In [165]:
df.head(10)

,date,bat_team_Chennai Super Kings,bat_team_Delhi Daredevils,bat_team_Kings XI Punjab,bat_team_Kolkata Knight Riders,bat_team_Mumbai Indians,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,...,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs,runs_last_5,wickets_last_5,total
32,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,0,5.1,59,0,222
33,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,1,5.2,59,1,222
34,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,1,5.3,59,1,222
35,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,1,5.4,59,1,222
36,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,1,5.5,58,1,222
37,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,61,1,5.6,58,1,222
38,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,62,1,6.1,55,1,222
39,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,63,1,6.2,52,1,222
40,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,64,1,6.3,47,1,222
41,2008-04-18,0,0,0,1,0,0,0,0,0,...,0,0,1,0,66,1,6.4,45,1,222

In [175]:
# # !pip install pickle

# import pickle

In [177]:
# with open("ipl.pkl","wb") as f:
#     pickle.dump(lr,f)